#!/usr/bin/env bash
# publish-latest-newsletter.sh — publish the latest Pinky newsletter to GitHub Pages
#
# Writes ~/solrey3.github.io/news/index.md so the latest dispatch is available at:
#   https://solrey3.github.io/news
#
# Usage:
#   scripts/publish-latest-newsletter.sh [path/to/newsletter.md]

set -euo pipefail

PINKY_DIR="${PINKY_DIR:-$HOME/pinky}"
PAGES_DIR="${PAGES_DIR:-$HOME/solrey3.github.io}"
NEWSLETTERS_DIR="$PINKY_DIR/raw/newsletters"
TARGET_DIR="$PAGES_DIR/news"
TARGET="$TARGET_DIR/index.md"
TARGET_REL="news/index.md"

newsletter="${1:-}"
if [[ -z "$newsletter" ]]; then
  newsletter=$(find "$NEWSLETTERS_DIR" -maxdepth 1 -type f -name '*.md' -printf '%T@ %p\n' \
    | sort -n \
    | tail -1 \
    | cut -d' ' -f2-)
fi

if [[ -z "$newsletter" || ! -f "$newsletter" ]]; then
  echo "[publish-news] No newsletter found to publish."
  exit 1
fi

if [[ ! -d "$PAGES_DIR/.git" ]]; then
  echo "[publish-news] GitHub Pages repo not found: $PAGES_DIR"
  exit 1
fi

mkdir -p "$TARGET_DIR"

python3 - "$newsletter" "$TARGET" <<'PY'
from pathlib import Path
import re
import sys

src = Path(sys.argv[1]).resolve()
dst = Path(sys.argv[2]).resolve()
text = src.read_text(encoding="utf-8")

frontmatter = ""
body = text
match = re.match(r"^---\s*\n(.*?)\n---\s*\n?(.*)$", text, re.DOTALL)
if match:
    frontmatter, body = match.groups()

def meta_value(key: str) -> str:
    pattern = rf"^{re.escape(key)}:\s*(.+?)\s*$"
    m = re.search(pattern, frontmatter, re.MULTILINE)
    if not m:
        return ""
    return m.group(1).strip().strip("'\"")

created = meta_value("created") or "unknown"
source_title = meta_value("title") or src.stem
out = f"""---
layout: page
title: Latest Dispatch
permalink: /news/
---

<!-- Auto-generated by ~/pinky/scripts/publish-latest-newsletter.sh. Do not edit by hand. -->

_Originally generated: {created}_  
_Source: `{src.name}`_

"""
out += body.rstrip() + "\n"

dst.write_text(out, encoding="utf-8")
print(f"[publish-news] Published {source_title} from {src} to {dst}")
PY

cd "$PAGES_DIR"

if git diff --quiet -- "$TARGET_REL" \
  && git diff --cached --quiet -- "$TARGET_REL" \
  && [[ -z "$(git ls-files --others --exclude-standard -- "$TARGET_REL")" ]]; then
  echo "[publish-news] No Pages changes to commit."
  exit 0
fi

git add "$TARGET_REL"
git commit -m "news: publish latest dispatch"
git pull --rebase origin master
git push origin master

echo "[publish-news] Pushed latest dispatch to GitHub Pages."
